[build]
  publish = "src"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/json/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"
